export const tHeader = [
  { id: 0, name: 'Member Name', width: '20%' },
  { id: 1, name: 'ID / Pass', width: '20%' },
  { id: 2, name: 'ROLE', width: '20%' },
  { id: 3, name: 'STATUS', width: '20%' },
  { id: 4, name: 'CREATION DATE', width: '20%' },
  { id: 5, name: 'ACTION', width: '20%' },
];

export const tBody = [
  {
    id: 0,
    thum: '/img/profile/profile-1.webp',
    name: 'Khuong Nguyen',
    email: 'khuong@mail.com',
    country: 'Viet Nam',
    pass: 'Can tho',
    role: 'ADMIN',
    status: 'ONLINE',
    createAt: '06/26/2021',
  },
  {
    id: 1,
    thum: '/img/profile/profile-2.webp',
    name: 'Thuan Dang',
    email: 'ThuanDMCE@mail.com',
    country: 'ThaiLand',
    pass: 'Bangkok',
    role: 'MEMBER',
    status: 'OFFLINE',
    createAt: '06/24/2021',
  },
  {
    id: 2,
    thum: '/img/profile/profile-3.webp',
    name: 'Tuan Minh',
    email: 'MinhVuxx@mail.com',
    country: 'Viet Nam',
    pass: 'Ha Noi',
    role: 'ADMIN',
    status: 'ONLINE',
    createAt: '05/26/2021',
  },
  {
    id: 3,
    thum: '/img/profile/profile-4.webp',
    name: 'Trung Hien',
    email: 'Map@mail.com',
    country: 'Viet Nam',
    pass: 'Sai Gon',
    role: 'MEMBER',
    status: 'OFFLINE',
    createAt: '04/22/2021',
  },
  {
    id: 5,
    thum: '/img/profile/profile-5.webp',
    name: 'Thanh Liem',
    email: 'LiemKhiet@mail.com',
    country: 'USA',
    pass: 'Hawaii',
    role: 'ADMIN',
    status: 'OFFLINE',
    createAt: '04/22/2021',
  },
  {
    id: 5,
    thum: '/img/profile/profile-6.webp',
    name: 'Minh Vo',
    email: 'Vovinam@mail.com',
    country: 'China',
    pass: 'Wuhan',
    role: 'MEMBER',
    status: 'ONLINE',
    createAt: '04/20/2021',
  },
];
