export const moackData = [
  {
    id: 0,
    thum: '/img/profile/profile-1.webp',
    name: 'Khuong Nguyen',
    email: 'khuong@mail.com',
    country: 'Viet Nam',
    pass: 'Can tho',
    role: true,
    status: true,
    createAt: '06/26/2021',
  },
  {
    id: 1,
    thum: '/img/profile/profile-2.webp',
    name: 'Thuan Dang',
    email: 'ThuanDMCE@mail.com',
    country: 'ThaiLand',
    pass: 'Bangkok',
    role: false,
    status: false,
    createAt: '06/24/2021',
  },
  {
    id: 2,
    thum: '/img/profile/profile-3.webp',
    name: 'Tuan Minh',
    email: 'MinhVuxx@mail.com',
    country: 'Viet Nam',
    pass: 'Ha Noi',
    role: true,
    status: true,
    createAt: '05/26/2021',
  },
  {
    id: 3,
    thum: '/img/profile/profile-4.webp',
    name: 'Trung Hien',
    email: 'Map@mail.com',
    country: 'Viet Nam',
    pass: 'Sai Gon',
    role: false,
    status: false,
    createAt: '04/22/2021',
  },
  {
    id: 5,
    thum: '/img/profile/profile-5.webp',
    name: 'Thanh Liem',
    email: 'LiemKhiet@mail.com',
    country: 'USA',
    pass: 'Hawaii',
    role: true,
    status: false,
    createAt: '04/22/2021',
  },
  {
    id: 5,
    thum: '/img/profile/profile-6.webp',
    name: 'Minh Vo',
    email: 'Vovinam@mail.com',
    country: 'China',
    pass: 'Wuhan',
    role: false,
    status: false,
    createAt: '04/20/2021',
  },
];
